### ISSUE TITLE
libmissing

### ISSUE THREAD

**Issue by histat** [DragonMinded/libnaomi#1]
before install lib
in Makfile.shared 
libmissing failed on non english envroment

I changed
libmissing = $(shell LANG=C ${LD} -l$(1) 2>&1 | grep "cannot find" | wc -l)

or better ?

**Comment by DragonMinded** [comment]
Hmm, yeah, forcing the language seems like it is necessary, I didn't think about tools that respect local language and `ld` doesn't offer another easy way to determine if a library exists.

**Comment by DragonMinded** [comment]
Seems according to this https://www.baeldung.com/linux/locale-environment-variables we need to set `LANG=en_US.UTF-8` at the beginning of the command. Does that successfully make libmissing work on your env? If not, we might need to set `LC_ALL=en_US.UTF-8` instead.

**Comment by histat** [comment]
no problem
it seems recently fixed
