### ISSUE TITLE
Best Practices for Adding Tools to Build Process

### ISSUE THREAD

**Issue by Softdrink117** [DragonMinded/libnaomi#4]
I've created a utility derived from your existing `tools/sprite.py` called `palette.py`, which is designed to ingest `.gpl` or `.pal` format palette files and construct color arrays that can be directly memcopied into the TA palette banks. `.gpl` and `.pal` are plaintext file formats that can be imported or exported from various graphics programs (GIMP, Aseprite, GraphicsGale, etc.), and there are also some online resources (such as [lospec.com](https://lospec.com/palette-list)) that host palettes in these formats for download.

It does not require any additional Python dependencies, and I've tested it standalone using the libnaomi pyenv without any issues. It works in both `RGBA1555` and `RGBA8888` modes, and supports 16 or 256-color palettes.

However, I'm running into a lot of trouble trying to integrate it into the actual build chain for my project. I tried to follow the example of the other tools (added to the `libnoami/tools` and `/opt/toolchains/naomi/tools/` directories, added `PAL2C_FILE` and `PAL2C` entries, added a `PALOBJS` patsubst to Makefile.shared, created build rules that call the program in the same style as those used in examples for `sprite.py`, etc.), but haven't had much luck; `make` keeps treating the files as if they are linker scripts.

If I manually run the tool to build palettes prior to running a build, everything works fine. It's just the actual automation and integration with `make` that seems to be the problem, and I'll admit the complexity of the build chain for this project is a bit beyond my current understanding.

It isn't clear to me if this is within the scope of libnaomi itself, so I didn't want to issue a PR (especially since there are still automation issues to sort out). But I've included the tool itself and the not-yet-functioning Makefile adjustments below.

Once again, thanks very much for any help you can provide!

-----

palette.py
```
#! /usr/bin/env python3
import argparse
import io
import os
import os.path
import sys
import textwrap
from enum import Enum

# Converts a .GPL or .PAL palette file into a .c file that defines the palette as a uint32_t array.
# This can then be memcpy'd into a TA palette bank directly
# Adapted from https://github.com/DragonMinded/libnaomi/blob/main/tools/sprite.py
def main() -> int:
    parser = argparse.ArgumentParser(
        description="Utility for converting .GPL Palette files to C include style."
    )
    parser.add_argument(
        'file',
        metavar='FILE',
        type=str,
        help='The output file we should generate.',
    )
    parser.add_argument(
        'palette',
        metavar='PALETTE',
        type=str,
        help='The palette file we should use to generate the output file.',
    )
    parser.add_argument(
        '--mode',
        metavar='MODE',
        type=str,
        help=(
            'The mode of the palette data to construct. Should match the video mode you are initializing.'
            'Options are "RGBA1555" and "RGBA8888".'
        ),
    )
    parser.add_argument(
        '--trans',
        nargs='?',
        const=0,
        default=0,
        metavar='TRANS',
        type=int,
        help=( 
            'The index of the transparent color in the palette. GPL and PAL palettes do not record transparency,'
            'so this must be passed as an option when converting. Default is 0 if not specified.'
        ),
    )
    args = parser.parse_args()

    PaletteType = Enum('PaletteType', ['Unknown', 'GPL', 'PAL'])

    paletteColors = []
    paletteName = ""
    colorCount = -1

    paletteType = PaletteType.Unknown

    with open(args.palette, "rt") as f:
        lines = f.readlines()

        for index, line in enumerate(lines, start=0):
            line = line.strip()
            
            # Make sure this is a valid GPL or PAL format file
            if index == 0:
                if line.lower().find("gimp palette") == 0:
                    paletteType = PaletteType.GPL
                    # print("Valid palette file")
                    continue
                elif line.lower().find("jasc-pal") == 0:
                    paletteType = PaletteType.PAL
                    continue
                else:
                    Exception(f"ERROR: Invalid or malformed palette file passed to palette.py! {args.plt}")

            # Parse GPL
            if paletteType == PaletteType.GPL:
                if line.find("Name:") != -1:
                    nameSplit = line.split(":")
                    paletteName = nameSplit[-1]
                    continue

                if line.find("Colors:") != -1:
                    colorCountSplit = line.split(":")
                    colorCount = int(colorCountSplit[-1])
                    continue

                # Ignore other commented lines
                if line.find("#") != -1:
                    continue
            
            # Parse PAL
            else:
                if index == 1:
                    continue
                if index == 2:
                    colorCount = int(line)
                    continue

            # Validate color count is either 16 or 256
            if colorCount != 16 and colorCount != 256:
                Exception(f"ERROR: Parsed color count does not align with supported NAOMI palette sizes! {colorCount} != 16 or 256")
            
            columns = line.split()
            if len(columns) >= 3:
                paletteColors.append([int(columns[0]), int(columns[1]), int(columns[2])])
                
    if colorCount != -1 and len(paletteColors) != colorCount:
        Exception(f"ERROR: Parsed color count does not match file declaration! {len(paletteColors)} != {colorCount}")

    # DEBUG: Print palette info
    # debug = "Parsed the following palette:\n"
    # debug += "Name: {0}\n".format(paletteName)
    # debug += "Colors: {0}\n".format(colorCount)
    # for pc in paletteColors:
    #     debug += "{0}\n".format(pc)
    # print(debug)

    # Convert the data to uint32 format, following the RGB1555 or RGB8888 macros:
    # #define RGB1555(r, g, b, a) ((((b) >> 3) & (0x1F << 0)) | (((g) << 2) & (0x1F << 5)) | (((r) << 7) & (0x1F << 10)) | (((a) << 8) & 0x8000))
    # #define RGB0888(r, g, b) (((b) & 0xFF) | (((g) << 8) & 0xFF00) | (((r) << 16) & 0xFF0000) | 0xFF000000)
    outColors = []
    mode = args.mode.lower()
    
    for index, pc in enumerate(paletteColors, start=0):
        alpha = 255
        if args.trans == index:
            alpha = 0
            
        if mode == "rgba1555": 
            outColors.append( (((pc[2] >> 3) & (0x1F << 0)) | ((pc[1] << 2) & (0x1F << 5)) | ((pc[0] << 7) & (0x1F << 10)) | ((alpha << 8) & 0x8000)) & 0xFFFFFFFF)
        elif mode == "rgba8888":
            outColors.append( (((pc[2] & 0xFF) << 0) | ((pc[1] & 0xFF) << 8) | ((pc[0] & 0xFF) << 16) | ((alpha & 0xFF) << 24)) & 0xFFFFFFFF)
        else:
            raise Exception(f"Unsupported depth {args.mode}!")
        

    rawSource = "".join(lines)

    name = os.path.basename(args.palette).replace('.', '_').replace('-', '_')

    outStr = [str(oc) for oc in outColors]

    cfile = f"""#include <stdint.h>

uint32_t __{name}_palette[{len(outStr)}] = {{
    {", ".join(outStr)}
}};
uint32_t *{name}_palette = __{name}_palette;

// Original {paletteType.name} file:
/*
{rawSource}
*/
    """

    with open(args.file, "w") as sfp:
        sfp.write(textwrap.dedent(cfile))

    return 0


if __name__ == "__main__":
    sys.exit(main())
```

Adjustments to Makefile.shared
```
... line 105:
# Set up various toolchain utilities.
PAL2C_FILE := ${TOOLS_DIR}palette.py
PAL2C := ${VENV_PYTHON3} ${PAL2C_FILE}

... line 169:
# Auto-compute objects based on sources we recognize. The rest of the sources will
# be assumed to be objects that we want to include.
CODEOBJS = $(patsubst %.cpp, build/%.o, $(patsubst %.s, build/%.o, $(patsubst %.c, build/%.o, ${SRCS})))
RAWOBJS = $(patsubst %.raw, build/%.o, ${CODEOBJS})
FONTOBJS = $(patsubst %.ttf, build/%.o, ${RAWOBJS})
IMGOBJS = $(patsubst %.jpg, build/%.o, $(patsubst %.png, build/%.o, ${FONTOBJS}))
PALOBJS = $(patsubst %.gpl, build/%.o, $(patsubst %.pal, build/%.o, ${IMGOBJS}))
OBJS = ${PALOBJS}
```

Buildrules for a project-specific Makefile
```
# Buildrules for Palette files for this project
build/%.o: %.gpl ${PAL2C_FILE}
	@mkdir -p $(dir $@)
	${PAL2C} build/$<.c --mode RGBA1555 $<
	${CC} -c build/$<.c -o $@

build/%.o: %.pal ${PAL2C_FILE}
	@mkdir -p $(dir $@)
	${PAL2C} build/$<.c --mode RGBA1555 $<
	${CC} -c build/$<.c -o $@
```

**Comment by DragonMinded** [comment]
Aside from the fact that you shouldn't need to add things manually to the env (`make install` should do that for you) this seems pretty reasonable. Having something that can generate palette files seems in line with the rest of the tooling. I tend to like things that are batteries-included as long as those batteries don't impose certain patterns. You shouldn't need to leave a comment as to where `palette.py` was adapted from (code here is public domain). Also, you should look at `IMG2BIN` as well and replicate that functionality here (so that palette files can also be stored in a ROMFS instead of compiled into the main binary). Do palette files not support alpha? Seems that isn't parsed out of those file formats and instead a single transparent color is selected.

From what you pasted I don't see why it wouldn't work properly. Perhaps put up a WIP PR and I can pull it down and tinker with it.

**Comment by Softdrink117** [comment]
Ah, it didn't even occur to me that `make install` would also hook up the tooling. Will definitely poke that a bit later!

Thanks for the rec for `IMG2BIN`, I'll dig into that when I have a moment. I can definitely see the value in supporting the ROMFS use case.

Alpha is one limitation of these particular formats - they don't support alpha in their standard implementation. (There is actually a variation of .GPL that adds support for alpha, but it seems to have _very_ limited adoption, and I'd rather make something that conforms to the actual standard.)

It seems like there are three other common formats for palette data that do support alpha:

- `.ase` (Adobe Swatch Exchange)
    - Not sure how I overlooked this one earlier, but supporting Adobe standards would probably be useful. Seems more complicated to parse, but I did find a couple examples of existing python implementations.
- `.png` 
    - Apparently it is somewhat common practice to simply import a PNG! It sounds like not all pixel art tools support this elegantly (EG: in several you the recommended workflow is literally "paste in a PNG layer and eyedropper select your colors from it"), but I imagine it would be quite simple to just load the first _n_ pixels of the PNG as palette data. The only catch is that it makes the buildrules a bit more complicated to set up per-project, since there is overlap with PNG sprite source files.
    - This is probably the most important one to add support for; the buildrule issue is easy to work around, and the utility is obvious.
- `.txt` 
    - Seems to only be supported by Paint.Net, so it's not as high a priority. But the actual format is just hex colors, so should be quite easy to add.

It should be pretty straightforward to add support for additional palette types to `palette.py`, so I'll work on that as well and come back with a PR once I'm a bit farther along.

Thanks!
